### ISSUE TITLE
[FEATURE REQUEST] Purpur support

### ISSUE THREAD

**Issue by ellitedev** [crbanman/papermc-lazymc-docker#4]
Environment variable for using [Purper](https://purpurmc.org/) instead of Paper

**Comment by Okazakee** [comment]
Hello, can you give me a brief explain of the benefits? I could insert that in my fork tho...

**Comment by Okazakee** [comment]
> Environment variable for using [Purper](https://purpurmc.org/) instead of Paper

I am happy to inform you that I've successfully supported that in my [fork](https://github.com/Okazakee/mcserver-lazymc-docker), hope to made you life easier.
