### ISSUE TITLE
rcon does not work

### ISSUE THREAD

**Issue by f0086** [crbanman/papermc-lazymc-docker#5]
I run the server with the following command:

```
sudo docker run -p 25565:25565 -p 25575:25575 -v $PWD/data:/papermc crbanman/papermc-lazymc:latest
```

The relevant config file changes in ```lazymc.toml```:
```
...
[rcon]
enabled = true
port = 25575
password = "abc"
randomize_password = false
...
```

After trying to access the rcon console, it failed:

```
$ mcrcon -H localhost -P 25575 -p abc
Error: recv() failed. Invalid packet size (-1).
Authentication failed!
```

To test that rcon works with lazymc, I started lazymc directly without docker with the same configuration from the ```./data``` directory, **which works fine**. So IMHO it is not a configuration issue.

The ```Dockerfile``` only ```EXPOSE```s 25565, so I've added ```EXPOSE 25575``` to the ```Dockerfile```, build it and test it with my built image, but this also did not work (same error, see above). Not sure how to debug this further. What's wrong here?

**Comment by timvisee** [comment]
I wonder if the RCON server binds the same host as the minecraft server.

What I mean by that, is if the Minecraft server is listening on `127.0.0.1` (localhost) it may not, along with RCON, accept outside connections.

Making the server listen on `0.0.0.0` may help?

**Comment by f0086** [comment]
You are absolutely right! That was the problem.
Setting the following setting in ```lazymc.toml``` will allow connecting through rcon. Thanks!

```
...
[server]
address = "0.0.0.0:25566"
...
```
